### ISSUE TITLE
Strange Error Codes

### ISSUE THREAD

**Issue by austinstig** [bsteinb/rsmpi#8]
I executed the send_receive.rs example. My GCC version is 4.9.2 on a cluster running CentOS 6. My MPICH is 3.1.4. The program seems to produce the correct output except that it is returning strange error codes from Status (see attached).  I also tried a few other examples and this behavior happened for them as well. Do you know what might be causing this? My rust-bindgen is using a libclang.so file instead of a libclang.a file but otherwise nothing else seems to be different.

[foo.txt](https://github.com/bsteinb/rsmpi/files/148417/foo.txt)

**Comment by bsteinb** [comment]
Yes, the error field of the status type is simply not filled with any meaningful information by the send and receive type functions. It might be filled with an error code in a situation where you are waiting for the completion of multiple non-blocking point to point operations. This part of MPI is not covered by the bindings yet. (See e.g. `MPI_Waitall()` on the list of unfinished features in the documentation of the `point_to_point` module.)

More generally, however, the default behavior of MPI is to abort the program on communication errors rather than returning an error code. The bindings do not change this default at the moment.

I should probably remove the `error()` getter function and the error field from the `Display` output of `Status`.

**Comment by austinstig** [comment]
Good to know. Thank you for the information.
